version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: GybLCvfdVzlyUIME08qc
      MINIO_SECRET_KEY: fqX4U6Xs8aAob945IsyORVGoUPXLpjye5uKRJLcN
    command: server /data
  client-backend:
    image: reports-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - SERVER_PORT= 8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/report_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest