version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: report_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: GybLCvfdVzlyUIME08qc
      MINIO_SECRET_KEY: fqX4U6Xs8aAob945IsyORVGoUPXLpjye5uKRJLcN
#    command: server /data