version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: report_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  client-backend:
    image: reports-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - minio/minio
    environment:
      - SERVER_PORT= 8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/report_db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: GybLCvfdVzlyUIME08qc
      MINIO_SECRET_KEY: fqX4U6Xs8aAob945IsyORVGoUPXLpjye5uKRJLcN
#    command: server /data