server:
  port: ${SERVER_PORT:8082}
spring:
#RABBITMQ Properties
  jpa:
    hibernate:
      jdbc.time_zone: Asia/Almaty
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:report_db}?currentSchema=report_schema
    username: ${DATASOURCE_USER:postgres}
#    password: ${DATASOURCE_PASSWORD:password}
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE:100}
      minimum-idle: 2
      leak-detection-threshold: 30000 # 30000 - 30 seconds
      auto-commit: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
#Minio Properties
#  minio:
#    url: ${MINIO_URL:http://127.0.0.1:9000}
#    bucket: ${MINIO_BUCKET:file-storage}
#    access-key: ${MINIO_ACCESS_KEY:GybLCvfdVzlyUIME08qc}
#    secret-key: ${MINIO_SECRET_KEY:fqX4U6Xs8aAob945IsyORVGoUPXLpjye5uKRJLcN}
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: ${MAX_FILE_SIZE:20MB}
#      max-request-size: ${MAX_REQUEST_SIZE:20MB}
#      file-size-threshold: ${FILE-SIZE-THRESHOLD:2KB}

  #Swagger Properties
springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}
  #Servlet Multipart Properties

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:exchange_report}
  queue: ${RABBITMQ_QUEUE:queue_report}
  routing_key: ${RABBITMQ_ROUTING_KEY:routing_key_report}


